# Generated by Django 4.2.3 on 2023-09-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Const',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ΔH1', models.FloatField(default=-20000, help_text='J/molA')),
                ('ΔH2', models.FloatField(default=-60000, help_text='J/molA')),
                ('cpA', models.FloatField(default=90, help_text='J/mol°C')),
                ('cpB', models.FloatField(default=90, help_text='J/mol°C')),
                ('cpC', models.FloatField(default=180, help_text='J/mol°C')),
                ('Ua', models.FloatField(default=4000, help_text='J/m³⋅s⋅°C')),
                ('Ta0', models.FloatField(default=373, help_text='K')),
                ('CT0', models.FloatField(default=0.1, help_text='mol/L')),
            ],
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FA', models.FloatField(default=100, help_text='mol/s')),
                ('FB', models.FloatField(default=0, help_text='mol/s')),
                ('FC', models.FloatField(default=0, help_text='mol/s')),
                ('T', models.FloatField(default=423, help_text='K')),
                ('V', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='E102',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W', models.FloatField(default=0)),
                ('X', models.FloatField(default=290)),
                ('p', models.FloatField(default=1)),
                ('PT0', models.FloatField(default=12, help_text='atm')),
                ('PH20', models.FloatField(default=18, help_text='atm')),
                ('PB0', models.FloatField(default=0, help_text='atm')),
            ],
        ),
        migrations.CreateModel(
            name='E122',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V', models.FloatField(default=0)),
                ('X', models.FloatField(default=0)),
                ('T0', models.FloatField(default=1035, help_text='K')),
                ('Ta0', models.FloatField(default=1250, help_text='K')),
            ],
        ),
        migrations.CreateModel(
            name='E124',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T0', models.FloatField(default=550, help_text='R')),
                ('XBM', models.FloatField(default=0)),
                ('XBE', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='E126',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ΔH1', models.FloatField(default=-55000, help_text='J/molA')),
                ('ΔH2', models.FloatField(default=-71500, help_text='J/molB')),
                ('cpA', models.FloatField(default=200, help_text='J/mol K')),
                ('cpB', models.FloatField(default=200, help_text='J/mol K')),
                ('cpC', models.FloatField(default=200, help_text='J/mol k')),
                ('UA', models.FloatField(default=40000, help_text='J/min⋅K')),
                ('Ta0', models.FloatField(default=330, help_text='K')),
                ('E1', models.FloatField(default=9900, help_text='cal/mol')),
                ('E2', models.FloatField(default=27000, help_text='cal/mol')),
                ('T0', models.FloatField(default=283, help_text='K')),
                ('Tf', models.FloatField(default=740, help_text='K')),
                ('CA0', models.FloatField(default=0.3, help_text='mol/L')),
                ('v0', models.FloatField(default=1000, help_text='L/min')),
                ('V', models.FloatField(default=10, help_text='L/min')),
            ],
        ),
        migrations.CreateModel(
            name='E127',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V', models.FloatField(default=10, help_text='L')),
                ('T', models.FloatField(default=300, help_text='K')),
                ('FA', models.FloatField(default=5, help_text='mol/min')),
                ('FB', models.FloatField(default=10, help_text='mol/min')),
                ('FC', models.FloatField(default=0, help_text='mol/min')),
                ('FD', models.FloatField(default=0, help_text='mol/min')),
                ('Ta0', models.FloatField(default=325, help_text='K')),
            ],
        ),
        migrations.CreateModel(
            name='E131',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X0', models.FloatField(default=0)),
                ('T0', models.FloatField(default=286, help_text='K')),
                ('t', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='E135',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.FloatField(default=0)),
                ('Ti', models.FloatField(default=290, help_text='K')),
                ('CAi', models.FloatField(default=1, help_text='mol/L')),
                ('CBi', models.FloatField(default=0, help_text='mol/L')),
                ('CCi', models.FloatField(default=0, help_text='mol/L')),
            ],
        ),
        migrations.CreateModel(
            name='P1216',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T0', models.FloatField(default=280, help_text='K')),
                ('XBM', models.FloatField(default=0)),
                ('XBE', models.FloatField(default=0)),
                ('Xeq', models.FloatField(default=0)),
                ('GT', models.FloatField(default=0, help_text='cal/mol')),
                ('RT', models.FloatField(default=0, help_text='cal/mol')),
            ],
        ),
        migrations.CreateModel(
            name='P1223',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V', models.FloatField(default=0)),
                ('T0', models.FloatField(default=300, help_text='K')),
                ('FA0', models.FloatField(default=5, help_text='mol/min')),
                ('FB0', models.FloatField(default=0, help_text='mol/min')),
                ('FC0', models.FloatField(default=0, help_text='mol/min')),
                ('Ta0', models.FloatField(default=320, help_text='K')),
            ],
        ),
    ]
