# Generated by Django 4.2.3 on 2023-10-10 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e122',
            name='T0',
            field=models.FloatField(default=1035, help_text='K', validators=[django.core.validators.MinValueValidator(1, message='O valor deve ser maior que 1'), django.core.validators.MaxValueValidator(2000, message='O valor deve ser menor que 2000')]),
        ),
        migrations.AlterField(
            model_name='e122',
            name='Ta0',
            field=models.FloatField(default=1250, help_text='K', validators=[django.core.validators.MinValueValidator(1, message='O valor deve ser maior que 1'), django.core.validators.MaxValueValidator(2000, message='O valor deve ser menor que 2000')]),
        ),
    ]
