# Generated by Django 4.2.3 on 2023-07-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0002_alter_pessoa_fa0_alter_pessoa_t0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='FA0',
            new_name='FA',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='FB0',
            new_name='FB',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='FC0',
            new_name='FC',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='T0',
            new_name='T',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='CT0',
        ),
    ]
