# Generated by Django 4.2.3 on 2023-08-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0003_rename_fa0_pessoa_fa_rename_fb0_pessoa_fb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FA', models.DecimalField(decimal_places=4, max_digits=10)),
                ('FB', models.DecimalField(decimal_places=4, max_digits=10)),
                ('FC', models.DecimalField(decimal_places=4, max_digits=10)),
                ('T', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
