# Generated by Django 4.2.3 on 2024-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0004_dtr1_dtr2_e103_e104_alter_e125_δh1_alter_e125_δh2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTR3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(default='[0, 0.2, 0.4, 0.6, 0.8, 1, 1.2, 1.4, 1.6, 1.8, 2, 2.2, 2.4, 2.6, 2.8]', help_text='min', max_length=1000)),
                ('C(t)', models.CharField(default='[0, 78, 156, 280, 313, 250, 188, 135, 94, 70, 47, 30, 19, 10, 0]', help_text='mg/dm³', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DTR4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(default='[0, 20, 40, 60, 80, 120, 160, 200, 240, 280, 320]', help_text='min', max_length=1000)),
                ('C(t)', models.CharField(default='[2000, 1050, 520, 280, 160, 61, 29, 16.4, 10, 6.4, 4]', help_text='mg/dm³', max_length=1000)),
            ],
        ),
    ]
