# Generated by Django 4.2.3 on 2023-08-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0005_alter_dados_fa_alter_dados_fb_alter_dados_fc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='V',
            field=models.FloatField(default=0),
        ),
    ]
