# Generated by Django 4.2.3 on 2023-08-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0008_const'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='const',
            name='CpA',
        ),
        migrations.RemoveField(
            model_name='const',
            name='deltaH1',
        ),
        migrations.RemoveField(
            model_name='const',
            name='deltaH2',
        ),
        migrations.AddField(
            model_name='const',
            name='ΔH1',
            field=models.FloatField(default=-20000, help_text='J/molA'),
        ),
        migrations.AddField(
            model_name='const',
            name='ΔH2',
            field=models.FloatField(default=-60000, help_text='J/molA'),
        ),
        migrations.AddField(
            model_name='dados',
            name='V',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='const',
            name='CT0',
            field=models.FloatField(default=0.1, help_text='mol/L'),
        ),
        migrations.AlterField(
            model_name='const',
            name='Ta',
            field=models.FloatField(default=373, help_text='K'),
        ),
        migrations.AlterField(
            model_name='const',
            name='Ua',
            field=models.FloatField(default=4000, help_text='J/m³⋅s⋅°C'),
        ),
        migrations.AlterField(
            model_name='const',
            name='cpB',
            field=models.FloatField(default=90, help_text='J/mol°C'),
        ),
        migrations.AlterField(
            model_name='const',
            name='cpC',
            field=models.FloatField(default=180, help_text='J/mol°C'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='FA',
            field=models.FloatField(help_text='mol/s'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='FB',
            field=models.FloatField(help_text='mol/s'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='FC',
            field=models.FloatField(help_text='mol/s'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='T',
            field=models.FloatField(help_text='K'),
        ),
        migrations.AddField(
            model_name='const',
            name='cpA',
            field=models.FloatField(default=90, help_text='J/mol°C'),
        ),
    ]
