# Generated by Django 4.2.3 on 2023-08-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0009_remove_const_cpa_remove_const_deltah1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='E126',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ΔH1', models.FloatField(default=-55000, help_text='J/molA')),
                ('ΔH2', models.FloatField(default=-71500, help_text='J/molB')),
                ('cpA', models.FloatField(default=200, help_text='J/mol K')),
                ('cpB', models.FloatField(default=200, help_text='J/mol K')),
                ('cpC', models.FloatField(default=200, help_text='J/mol k')),
                ('UA', models.FloatField(default=40000, help_text='J/min⋅K')),
                ('Ta', models.FloatField(default=330, help_text='K')),
                ('E1', models.FloatField(default=9900, help_text='cal/mol')),
                ('E2', models.FloatField(default=27000, help_text='cal/mol')),
                ('T0', models.FloatField(default=283, help_text='K')),
                ('CA0', models.FloatField(default=0.3, help_text='mol/L')),
                ('v0', models.FloatField(default=1000, help_text='L/min')),
                ('V', models.FloatField(default=10, help_text='L/min')),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
