# Generated by Django 4.2.3 on 2023-08-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0010_e126_delete_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='e126',
            name='Tf',
            field=models.FloatField(default=740, help_text='K'),
        ),
    ]
