# Generated by Django 4.2.3 on 2023-08-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0011_e126_tf'),
    ]

    operations = [
        migrations.CreateModel(
            name='E127',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V', models.FloatField(default=10, help_text='L')),
                ('T', models.FloatField(default=300, help_text='K')),
                ('FA', models.FloatField(default=5, help_text='mol/L')),
                ('FB', models.FloatField(default=10, help_text='mol/L')),
                ('FC', models.FloatField(default=0, help_text='mol/L')),
                ('FD', models.FloatField(default=0, help_text='mol/L')),
                ('Ta', models.FloatField(default=325, help_text='K')),
            ],
        ),
    ]
