# Generated by Django 4.2.3 on 2023-08-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0012_e127'),
    ]

    operations = [
        migrations.CreateModel(
            name='E131',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X0', models.FloatField(default=0)),
                ('T0', models.FloatField(default=286, help_text='K')),
                ('t', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='e127',
            name='FA',
            field=models.FloatField(default=5, help_text='mol/min'),
        ),
        migrations.AlterField(
            model_name='e127',
            name='FB',
            field=models.FloatField(default=10, help_text='mol/min'),
        ),
        migrations.AlterField(
            model_name='e127',
            name='FC',
            field=models.FloatField(default=0, help_text='mol/min'),
        ),
        migrations.AlterField(
            model_name='e127',
            name='FD',
            field=models.FloatField(default=0, help_text='mol/min'),
        ),
    ]
