# Generated by Django 4.2.3 on 2023-08-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0013_e131_alter_e127_fa_alter_e127_fb_alter_e127_fc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='E135',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.FloatField(default=0)),
                ('Ti', models.FloatField(default=290, help_text='K')),
                ('CAi', models.FloatField(default=1, help_text='mol/L')),
                ('CBi', models.FloatField(default=0, help_text='mol/L')),
                ('CCi', models.FloatField(default=0, help_text='mol/L')),
            ],
        ),
    ]
