# Generated by Django 4.2.3 on 2023-08-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0014_e135'),
    ]

    operations = [
        migrations.CreateModel(
            name='E102',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W', models.FloatField(default=0)),
                ('X', models.FloatField(default=290)),
                ('p', models.FloatField(default=1)),
                ('PT0', models.FloatField(default=12, help_text='atm')),
                ('PH20', models.FloatField(default=18, help_text='atm')),
                ('PB0', models.FloatField(default=0, help_text='atm')),
            ],
        ),
    ]
