# Generated by Django 4.2.3 on 2023-08-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0015_e102'),
    ]

    operations = [
        migrations.CreateModel(
            name='E124',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T0', models.FloatField(default=550)),
                ('XBM', models.FloatField(default=0)),
                ('XBE', models.FloatField(default=0)),
            ],
        ),
    ]
