# Generated by Django 4.2.3 on 2023-08-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0016_e124'),
    ]

    operations = [
        migrations.CreateModel(
            name='E122',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V', models.FloatField(default=0)),
                ('X', models.FloatField(default=0)),
                ('T0', models.FloatField(default=1035)),
                ('Ta0', models.FloatField(default=1250)),
            ],
        ),
        migrations.AlterField(
            model_name='e124',
            name='T0',
            field=models.FloatField(default=550, help_text='°R'),
        ),
    ]
