# Generated by Django 4.2.3 on 2023-08-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0017_e122_alter_e124_t0'),
    ]

    operations = [
        migrations.CreateModel(
            name='P1216',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T0', models.FloatField(default=280, help_text='K')),
                ('XBM', models.FloatField(default=0)),
                ('XBE', models.FloatField(default=0)),
                ('Xeq', models.FloatField(default=0)),
                ('GT', models.FloatField(default=0, help_text='cal/mol')),
                ('RT', models.FloatField(default=0, help_text='cal/mol')),
            ],
        ),
        migrations.AlterField(
            model_name='e122',
            name='T0',
            field=models.FloatField(default=1035, help_text='K'),
        ),
        migrations.AlterField(
            model_name='e122',
            name='Ta0',
            field=models.FloatField(default=1250, help_text='K'),
        ),
    ]
