# Generated by Django 4.2.3 on 2023-08-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0018_p1216_alter_e122_t0_alter_e122_ta0'),
    ]

    operations = [
        migrations.AddField(
            model_name='p1216',
            name='TEE',
            field=models.FloatField(default=0),
        ),
    ]
