# Generated by Django 4.2.3 on 2023-08-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0019_p1216_tee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p1216',
            name='TEE',
        ),
    ]
