# Generated by Django 4.2.3 on 2023-08-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0020_remove_p1216_tee'),
    ]

    operations = [
        migrations.CreateModel(
            name='P1223',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V', models.FloatField(default=0)),
                ('T0', models.FloatField(default=300, help_text='K')),
                ('FA0', models.FloatField(default=5, help_text='mol/min')),
                ('FB0', models.FloatField(default=0, help_text='mol/min')),
                ('FC0', models.FloatField(default=0, help_text='mol/min')),
                ('Ta0', models.FloatField(default=320, help_text='K')),
            ],
        ),
    ]
